In [8]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv(r"C:\Users\Anchal paswan\Desktop\AI_ML\Python\Daily\people.csv")
data

    Age  Gender   Hometown  Height  Qualification Smoker
0    45    Male     Mumbai     167       Graduate    Yes
1    23  Female     Mumbai     170       Graduate     No
2    27    Male     Mumbai     175  Post-graduate     No
3    34    Male      Delhi     155       Graduate     No
4    43  Female     Mumbai     157  Post-graduate    Yes
5    34    Male      Delhi     167        Diploma    Yes
6    44  Female     Mumbai     165       Graduate    Yes
7    56  Female      Delhi     170        Diploma    Yes
8    34    Male      Delhi     175  Post-graduate     No
9    49  Female  Bangalore     162  Post-graduate    Yes
10   35    Male  Bangalore     160       Graduate     No
11   28  Female     Mumbai     165        Diploma     No
12   54    Male      Delhi     170        Diploma    Yes
13   59  Female     Mumbai     175       Graduate     No
14   54    Male  Bangalore     175        Diploma    Yes
15   43  Female     Mumbai     155  Post-graduate     No
16   56  Female     Mumbai     151       Graduate     No
17   41    Male  Bangalore     180        Diploma     No
18   56    Male      Delhi     182       Graduate    Yes
19   53    Male  Bangalore     156  Post-graduate    Yes
20   21  Female  Bangalore     158  Post-graduate     No

In [12]:
pd.crosstab(data.Gender , data.Smoker , values =data.Age , aggfunc = "mean",rownames = ["gen"] , colnames = ['Smokerss'])

Smokerss         No        Yes
gen
Female    38.333333  48.000000
Male      34.200000  49.333333

In [19]:
duplicates = data[data.duplicated(keep = False)]
print(duplicates)

Empty DataFrame
Columns: [Age, Gender, Hometown, Height, Qualification]
Index: []

In [ ]:
data.drop(index=[2,4] , columns = ["Smoker"] , )

KeyError: '[2, 4] not found in axis'

MAP AND REPLACE

In [26]:
words = ["anchal" , "shubh" , "anuj"]
list(map(lambda x: x.capitalize() , words))

['Anchal', 'Shubh', 'Anuj']

In [27]:
names = [x.capitalize() for x in words]
print(names)

['Anchal', 'Shubh', 'Anuj']

In [ ]:
# create a dictionary
import pandas as pd
data = { 'Name':['Anne','Bobby','James','Lewis','Ross','Cathrine',
            'Anne','Bobby','Jack','Alisa','Alex','Cathrine'],
    'Company':['Apple','Walmart','Walmart','Intel','Apple','Walmart','Apple',
               'Cognizant','Apple','Apple','Cognizant','Walmart'],
    'Salary':[8500, 6300, 5500, 7400, 3100, 7700, 8500, 6300, 4200, 6200, 8900, 7700]}

# create a DataFrame
df_employee = pd.DataFrame(data, columns=['Name','Company','Salary'])
df_employee

In [28]:
import pandas as pd

data = {
    "Country": [
        "India",
        "China",
        "United States",
        "Indonesia",
        "Pakistan",
        "Brazil"
    ],
    "Population": [
        1438000000,
        1410000000,
        340000000,
        281000000,
        252000000,
        212000000
    ]
}

df = pd.DataFrame(data)

print(df)

         Country  Population
0          India  1438000000
1          China  1410000000
2  United States   340000000
3      Indonesia   281000000
4       Pakistan   252000000
5         Brazil   212000000

In [30]:
capitals = {
    "India" : "Delhi",
    "China" : "Bejing",
    "United States" : "NWC",
    "Indonesia" : "Jakarta",
    "Pakistan": "Lahore ", 
    "Brazil":"Brasillia"
}

In [31]:
df["capital"] = df.Country.map(capitals)
df

         Country  Population    capital
0          India  1438000000      Delhi
1          China  1410000000     Bejing
2  United States   340000000        NWC
3      Indonesia   281000000    Jakarta
4       Pakistan   252000000    Lahore
5         Brazil   212000000  Brasillia